# Generated by Django 4.1 on 2022-10-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoessize',
            name='shoe',
        ),
        migrations.AddField(
            model_name='shoes',
            name='color',
            field=models.CharField(default='Blue', max_length=100),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size',
            field=models.CharField(default='US 10', max_length=100),
        ),
        migrations.DeleteModel(
            name='ShoesColor',
        ),
        migrations.DeleteModel(
            name='ShoesSize',
        ),
    ]
