# Generated by Django 4.1 on 2022-10-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_remove_shoessize_shoe_shoes_color_shoes_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
