# Generated by Django 4.1 on 2022-10-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_alter_shoes_color_alter_shoes_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
