# Generated by Django 4.1 on 2022-10-29 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_alter_shoes_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size',
        ),
        migrations.CreateModel(
            name='ShoesSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoes')),
            ],
        ),
        migrations.CreateModel(
            name='ShoesColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoes')),
            ],
        ),
    ]
