# Generated by Django 4.1 on 2022-10-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_remove_shoes_color_remove_shoes_size_shoessize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoecart',
            name='color_selected_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shoes.shoescolor'),
        ),
        migrations.AddField(
            model_name='shoecart',
            name='size_selected_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shoes.shoessize'),
        ),
    ]
