# Generated by Django 4.1 on 2022-10-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_shoecart_color_selected_id_shoecart_size_selected_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoecart',
            name='color_selected_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoescolor'),
        ),
        migrations.AlterField(
            model_name='shoecart',
            name='size_selected_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoessize'),
        ),
    ]
